//! THE single place that knows OpenAI Codex **execpolicy** `.rules` syntax.
//!
//! Validated against `codex execpolicy check` on the Codex version pinned
//! in `examples/integrations/codex/README.md` (the single place the
//! version is recorded). The confirmed contract:
//!
//! - `prefix_rule(pattern, decision, justification?, match?, not_match?)`.
//! - `pattern` is an argv prefix. Each position is a string (literal) or a
//!   non-empty `list[str]` of alternatives. `["curl"]` matches `curl` with
//!   any trailing args; `["rm", "-rf"]` matches `rm -rf ...`. An **empty
//!   list is invalid** (`["curl", []]` is rejected) — it is NOT a wildcard.
//! - `decision` is one of `allow` / `prompt` / `forbidden` (`deny` is
//!   rejected).
//! - `match` / `not_match` are optional **parse-time assertions**: each
//!   example may be a shell string or an argv list; if a `match` example
//!   fails to match (or a `not_match` example matches), the file is
//!   rejected. So a self-consistent file is itself a round-trip test.
//!
//! The compiler emits only literal positions (no alternatives), so a
//! pattern here is a plain `Vec<String>`.

use crate::rules_compiler::CompileReport;

/// execpolicy decision. Strictest-wins at evaluation time:
/// `Forbidden` > `Prompt` > `Allow` (mirrors the APL overlay merge).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecDecision {
    Allow,
    Prompt,
    Forbidden,
}

impl ExecDecision {
    /// The literal decision strings execpolicy expects.
    pub fn as_str(self) -> &'static str {
        match self {
            ExecDecision::Allow => "allow",
            ExecDecision::Prompt => "prompt",
            ExecDecision::Forbidden => "forbidden",
        }
    }
}

/// One compiled command-prefix rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrefixRule {
    /// argv prefix the rule matches; each entry is a literal position.
    /// `["curl"]` matches `curl` with any trailing args; `["rm", "-rf"]`
    /// matches `rm -rf ...`. Never empty, and never contains an empty
    /// inner list (which execpolicy rejects).
    pub pattern: Vec<String>,
    pub decision: ExecDecision,
    /// Human justification; surfaced by Codex on prompt/deny. Carries the
    /// originating APL policy name + reason so the prompt cites the source.
    /// execpolicy requires a non-empty string when present.
    pub justification: String,
    /// argv examples that MUST match the pattern (parse-time assertion).
    pub match_examples: Vec<Vec<String>>,
    /// argv examples that MUST NOT match the pattern (parse-time assertion).
    pub not_match_examples: Vec<Vec<String>>,
}

/// Escape a string for a Starlark double-quoted literal.
fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Render an argv vector as a Starlark list of strings: `["a", "b"]`.
fn render_argv(argv: &[String]) -> String {
    let items: Vec<String> = argv.iter().map(|a| quote(a)).collect();
    format!("[{}]", items.join(", "))
}

/// Render a list of argv vectors: `[["a"], ["b", "c"]]`.
fn render_argv_list(list: &[Vec<String>]) -> String {
    let items: Vec<String> = list.iter().map(|argv| render_argv(argv)).collect();
    format!("[{}]", items.join(", "))
}

/// Render a single `prefix_rule(...)` call.
pub fn render_rule(rule: &PrefixRule) -> String {
    format!(
        "prefix_rule(\n    \
         pattern = {},\n    \
         decision = {},\n    \
         justification = {},\n    \
         match = {},\n    \
         not_match = {},\n)\n",
        render_argv(&rule.pattern),
        quote(rule.decision.as_str()),
        quote(&rule.justification),
        render_argv_list(&rule.match_examples),
        render_argv_list(&rule.not_match_examples),
    )
}

/// Render the file header: provenance, drift hash, coverage summary.
fn render_header(bundle_sha256: &str, report: &CompileReport) -> String {
    format!(
        "# Generated by IAGA Sentinel (`iaga-codex export-rules`) — DO NOT EDIT BY HAND.\n\
         # Source APL bundle SHA-256: {bundle}\n\
         # Static execpolicy layer: {rules} prefix rule(s) compiled, {runtime} policy(ies) runtime-only.\n\
         # The hash above makes drift between this file and the APL bundle detectable.\n\
         # Syntax validated against `codex execpolicy check`; see ADR 0022 and the integration README for the pinned Codex version.\n\n",
        bundle = bundle_sha256,
        rules = report.rules.len(),
        runtime = report.runtime_only.len(),
    )
}

/// Render the complete `.rules` file: header, every compiled rule, then a
/// trailing comment block listing the policies that stay runtime-only so
/// the static artifact itself documents what it does NOT cover.
pub fn render_rules_file(bundle_sha256: &str, report: &CompileReport) -> String {
    let mut out = render_header(bundle_sha256, report);
    for rule in &report.rules {
        out.push_str(&render_rule(rule));
        out.push('\n');
    }
    if !report.runtime_only.is_empty() {
        out.push_str(
            "# Runtime-only policies (no static command-prefix equivalent; enforced by the\n\
             # `iaga-codex hook` gate against POST /v1/inspect, not by this file):\n",
        );
        for ro in &report.runtime_only {
            out.push_str(&format!("#   - {}: {}\n", ro.policy_name, ro.reason));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quotes_escape_specials() {
        assert_eq!(quote(r#"a"b\c"#), r#""a\"b\\c""#);
    }

    #[test]
    fn renders_a_forbidden_rule_with_bare_program() {
        let rule = PrefixRule {
            pattern: vec!["curl".to_string()],
            decision: ExecDecision::Forbidden,
            justification: "IAGA Sentinel: no_egress. Use the proxy.".to_string(),
            match_examples: vec![vec!["curl".to_string()]],
            not_match_examples: vec![vec!["true".to_string()]],
        };
        let text = render_rule(&rule);
        // No empty inner list: a bare program is `["curl"]`, never `["curl", []]`.
        assert!(text.contains(r#"pattern = ["curl"]"#));
        assert!(text.contains(r#"decision = "forbidden""#));
        assert!(text.contains(r#"justification = "IAGA Sentinel: no_egress. Use the proxy.""#));
        assert!(text.contains(r#"match = [["curl"]]"#));
        assert!(text.contains(r#"not_match = [["true"]]"#));
    }

    #[test]
    fn renders_literal_arg_prefix_as_plain_strings() {
        let rule = PrefixRule {
            pattern: vec!["rm".to_string(), "-rf".to_string()],
            decision: ExecDecision::Prompt,
            justification: "IAGA Sentinel: confirm_rm".to_string(),
            match_examples: vec![vec!["rm".to_string(), "-rf".to_string()]],
            not_match_examples: vec![vec!["true".to_string()]],
        };
        let text = render_rule(&rule);
        // Literal positions are plain strings, not single-element alt lists.
        assert!(text.contains(r#"pattern = ["rm", "-rf"]"#));
        assert!(text.contains(r#"decision = "prompt""#));
    }
}
