//! Best-effort migration of a legacy YAML/JSON `SentinelConfig` into a Dictum
//! overlay (`iaga policy migrate`).
//!
//! ponytail: this is a *draft generator*, not a byte-perfect transpiler. A
//! Dictum overlay only ever tightens the decision (stricter-wins), so the one
//! thing that maps cleanly is a per-tool `max_decision` cap of Review or Block.
//! Everything the overlay context cannot express — agent profiles, roles,
//! approved-tool allowlists, domain allowlists, per-action-type restrictions —
//! is surfaced as a `// TODO: manual review` marker rather than guessed. The
//! output is a starting point a human reviews and completes.
//!
//! Overlay context (see `pipeline::dictum_overlay`): `agent.{id,framework}`,
//! `action.{kind,tool_name,payload}`, `workspace.{id,allowlist}`,
//! `risk.{score,decision}`.

use crate::core::types::{GovernanceDecision, SentinelConfig};

/// Render a legacy config as Dictum source. Pure and deterministic.
pub fn to_dictum(config: &SentinelConfig) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `iaga policy migrate`.\n");
    out.push_str("// A Dictum overlay only *tightens* decisions (stricter-wins), so only the\n");
    out.push_str("// Review/Block tool caps below are emitted; Allow is the default baseline\n");
    out.push_str("// and needs no rule. Review every `TODO` before loading this overlay.\n\n");

    let mut emitted = 0usize;
    for ws in &config.workspaces {
        for tool in &ws.tools {
            let verdict = match tool.max_decision {
                GovernanceDecision::Block => "block",
                GovernanceDecision::Review => "review",
                // A tool that only *requires* human review still tightens to review.
                GovernanceDecision::Allow if tool.requires_human_review => "review",
                // Allow with no review flag is the baseline; nothing to tighten.
                GovernanceDecision::Allow => continue,
            };
            let name = sanitize(&format!("ws_{}_tool_{}", ws.workspace_id, tool.tool_name));
            out.push_str(&format!("policy \"{name}\" {{\n"));
            out.push_str(&format!("  when workspace.id == \"{}\"\n", quote(&ws.workspace_id)));
            out.push_str(&format!(
                "   and action.tool_name == \"{}\"\n",
                quote(&tool.tool_name)
            ));
            out.push_str(&format!(
                "  then {verdict}, reason=\"migrated tool cap for {} in workspace {}\"\n",
                quote(&tool.tool_name),
                quote(&ws.workspace_id)
            ));
            out.push_str("}\n\n");
            emitted += 1;

            if !tool.allowed_action_types.is_empty() {
                out.push_str(&format!(
                    "// TODO: manual review - tool '{}' restricted allowed action types to {:?}; \
                     the overlay above fires on the tool name only, not per action kind.\n\n",
                    tool.tool_name, tool.allowed_action_types
                ));
            }
        }
    }

    if emitted == 0 {
        out.push_str("// (no Review/Block tool caps found — nothing to tighten)\n\n");
    }

    if !config.profiles.is_empty() {
        out.push_str(&format!(
            "// TODO: manual review - {} agent profile(s) (roles, approved tools/secrets, \
             baseline action types) are not expressible in the Dictum overlay context and \
             were not migrated.\n",
            config.profiles.len()
        ));
    }

    out
}

/// A safe Dictum policy identifier: keep alphanumerics and underscores, collapse
/// everything else to `_`.
fn sanitize(raw: &str) -> String {
    raw.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Minimal escaping for a value emitted inside a Dictum string literal. Real
/// tool names / workspace ids are simple identifiers; this only guards the rare
/// embedded quote or backslash so the output stays parseable.
fn quote(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::types::{
        ActionType, AgentProfile, AgentRole, ProtocolKind, ToolPolicy, WorkspacePolicy,
    };

    fn config_with_tool(max_decision: GovernanceDecision) -> SentinelConfig {
        SentinelConfig {
            profiles: vec![],
            vault: vec![],
            workspaces: vec![WorkspacePolicy {
                workspace_id: "ws-01".into(),
                tenant_id: None,
                allowed_protocols: vec![ProtocolKind::Mcp],
                tools: vec![ToolPolicy {
                    tool_name: "http.post".into(),
                    allowed_action_types: vec![ActionType::Http],
                    max_decision,
                    requires_human_review: false,
                }],
                allowed_domains: vec![],
                threshold_block: 70,
                threshold_review: 35,
            }],
        }
    }

    #[test]
    fn block_tool_becomes_block_policy() {
        let dictum = to_dictum(&config_with_tool(GovernanceDecision::Block));
        assert!(dictum.contains("then block"), "got:\n{dictum}");
        assert!(dictum.contains("action.tool_name == \"http.post\""));
        // The emitted overlay must parse and type-check.
        iaga_sentinel_dictum::compile_with_types(&dictum)
            .expect("migrated overlay should parse + type-check");
    }

    #[test]
    fn allow_tool_emits_no_rule_but_stays_valid() {
        let dictum = to_dictum(&config_with_tool(GovernanceDecision::Allow));
        assert!(!dictum.contains("policy \""), "allow cap should emit no policy");
        // An overlay of only comments is still a valid (empty) program.
        let (program, _) = iaga_sentinel_dictum::compile_with_types(&dictum)
            .expect("comment-only overlay should type-check");
        assert_eq!(program.policies.len(), 0);
    }

    #[test]
    fn profiles_are_flagged_for_manual_review() {
        let mut config = config_with_tool(GovernanceDecision::Review);
        config.profiles.push(AgentProfile {
            agent_id: "a-1".into(),
            tenant_id: None,
            workspace_id: "ws-01".into(),
            framework: "openai".into(),
            role: AgentRole::Builder,
            approved_tools: vec!["http.post".into()],
            approved_secrets: vec![],
            baseline_action_types: vec![ActionType::Http],
            tool_trust: 0.7,
        });
        let dictum = to_dictum(&config);
        assert!(dictum.contains("TODO: manual review"));
        assert!(dictum.contains("agent profile"));
        iaga_sentinel_dictum::compile_with_types(&dictum).expect("still valid Dictum");
    }
}
